export const MSG = {
  STARTPAGE_SCRIPT_STATUS: "STARTPAGE_SCRIPT_STATUS",
  STARTPAGE_CONTEXT_FOUND: "STARTPAGE_CONTEXT_FOUND",
  SESSION_UPDATED: "SESSION_UPDATED",
  REQUEST_RUN_FOR_TAB: "REQUEST_RUN_FOR_TAB",
  SIDEBAR_FOLLOW_UP: "SIDEBAR_FOLLOW_UP",
  SIDEBAR_GET_STATE: "SIDEBAR_GET_STATE",
  OPTIONS_GET_SETTINGS: "OPTIONS_GET_SETTINGS",
  OPTIONS_SAVE_SETTINGS: "OPTIONS_SAVE_SETTINGS",
  OPTIONS_SET_API_KEY: "OPTIONS_SET_API_KEY",
  OPTIONS_DELETE_API_KEY: "OPTIONS_DELETE_API_KEY",
  OPTIONS_VALIDATE_API_KEY: "OPTIONS_VALIDATE_API_KEY"
};
